### ISSUE TITLE
Wrong warning message on PHP8 BC Break Scanner

### ISSUE THREAD

**Issue by schmop** [PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices#21]
https://github.com/PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/blob/main/ch11/php8_bc_break_scanner_config.php#L217

> WARNING: using the "@" operator to suppress warnings no longer works in PHP 8.

The actual changes on PHP 8 considering the "@" operator are to no longer ignore and suppress errors. Warnings can still be suppressed.

**Comment by dbierer** [comment]
What you are saying is true.  However, the message cited above says nothing about not being able to suppress warnings.  To suppress warnings all you need to do is to set error_reporting to E_ALL ^ E_WARNING.  This message specifically addresses bad usage of the @ operator.
