### ISSUE TITLE
Unable to start the docker-compose images

### ISSUE THREAD

**Issue by mkj0** [PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices#22]
Hi,

Following the instructions as described, (code saved into a folder called "repo"), when I build and start the images in docker, both the images (PHP7 & 8) have the error "standard_init_linux.go:228: exec user process caused: no such file or directory" and are constantly restarting.

I can only guess that it might be having trouble finding the source folder, but I'm running the scripts from a command prompt in the root of the "repo" folder, and there's no errors during the build process.

I'm relatively new to Docker, so that's possibly not helping me.

Running Windows 11, and Docker Desktop 4.1.1.

Any suggestions would be appreciated.

Thanks,

Mike

**Comment by pingumen96** [comment]
Hello,
I'm having a similar problem and I already tried what you said.
I cloned the repo on Windows 11, on an external drive and I'm having the following error:
```
[+] Running 2/0
 - Container php8_tips_php8  Created                                                                                                             0.0s
 - Container php8_tips_php7  Created                                                                                                             0.0s
Attaching to php8_tips_php7, php8_tips_php8
php8_tips_php7  | exec /tmp/startup.sh: no such file or directory
php8_tips_php7 exited with code 0
php8_tips_php8  | exec /tmp/startup.sh: no such file or directory
php8_tips_php7  | exec /tmp/startup.sh: no such file or directory
php8_tips_php7  | exec /tmp/startup.sh: no such file or directory
...
```
