### ISSUE TITLE
 [Composer\Downloader\TransportException]                                          The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection refused

### ISSUE THREAD

**Issue by lse123** [PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices#28]
DO YOU HAVE ANY IDEA FOR Can not run successfully the **docker-compose build** command:...???

leonidas@ubuntu:~/Documents/DockerPHP8x/repo$ **sudo docker-compose build**
...
...
 ---> Running in 44fc7480bcf7
Updating Composer 1.x ...

                                                                                                                  
  [Composer\Downloader\TransportException]                                                                        
  **The "https://getcomposer.org/versions" file could not be downloaded**: failed to open stream: Connection refused  
                                                                                                                  

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--set-channel-only] [--] [<version>]

**Comment by dbierer** [comment]
# RESPONSE
Leonidas,

I was unable to duplicate the problem.  The output from Ubuntu 20.04 is shown below.  Can you please try this:
```
docker pull unlikelysource/php8_tips_7_1_interrim:latest
docker run -it unlikelysource/php8_tips_7_1_interrim:latest /bin/bash 
ping -c3 getcomposer.org
composer update
```
It looks like a connection issue. Let me know what you see.  I'll keep this issue open until you respond.
--db

# OUTPUT FROM UBUNTU 20.04:
```
ned@ned:~/Repos/packt/PHP-8-Programming-Tips-Tricks-and-Best-Practices$ docker-compose build
Building php8-tips-php7
Step 1/7 : FROM unlikelysource/php8_tips_7_1_interrim:latest
 ---> a47711b81daf
Step 2/7 : MAINTAINER doug@unlikelysource.com
 ---> Using cache
 ---> 4e23bfb722d5
Step 3/7 : COPY php8_tips.sql /tmp/php8_tips.sql
 ---> Using cache
 ---> 0651d2da95e7
Step 4/7 : COPY startup.sh /tmp/startup.sh
 ---> Using cache
 ---> 08c1186503e7
Step 5/7 : RUN     echo "Restoring sample database ..." &&     /etc/init.d/mysql start &&     sleep 7 &&     mysql -uroot -e "SOURCE /tmp/php8_tips.sql;" php8_tips
 ---> Running in af83069c0f70
Restoring sample database ...
  *  Starting MySQL daemon...                                          [  OK  ]
Removing intermediate container af83069c0f70
 ---> af41b004520a
Step 6/7 : RUN     echo "Updating Composer 1.x ..." &&     /usr/bin/composer self-update
 ---> Running in d823c7d6343c
Updating Composer 1.x ...
A new stable major version of Composer is available (2.2.7), run "composer self-update --2" to update to it. See also https://getcomposer.org/2
Updating to version 1.10.25 (1.x channel).
   Downloading (100%)         
Use composer self-update --rollback to return to version 1.10.23
Removing intermediate container d823c7d6343c
 ---> 4ac223333302
Step 7/7 : CMD /tmp/startup.sh
 ---> Running in 2fb675e6c74c
Removing intermediate container 2fb675e6c74c
 ---> 3a0659451809
Successfully built 3a0659451809
Successfully tagged php8tips/php8_tips_image_php7_latest:latest
Building php8-tips-php8
Step 1/8 : FROM unlikelysource/php8_tips_8_0_interrim:latest
 ---> b2b0c48e52b8
Step 2/8 : MAINTAINER doug@unlikelysource.com
 ---> Using cache
 ---> 5513f005e2c5
Step 3/8 : COPY php8_tips.sql /tmp/php8_tips.sql
 ---> ea58072c443d
Step 4/8 : COPY startup.sh /tmp/startup.sh
 ---> 2d9a0cfdd59f
Step 5/8 : RUN     echo "Restoring sample database ..." &&     /etc/init.d/mysql start &&     sleep 7 &&     mysql -uroot -e "SOURCE /tmp/php8_tips.sql;" php8_tips
 ---> Running in a6bd7b6ef26d
Restoring sample database ...
  *  Starting MySQL daemon...                                          [  OK  ]
Removing intermediate container a6bd7b6ef26d
 ---> bed36a604c9d
Step 6/8 : RUN     echo "Updating Composer 2.x ..." &&     /usr/bin/composer self-update
 ---> Running in 60cbf23b305b
Updating Composer 2.x ...
Upgrading to version 2.2.7 (stable channel).
   
Use composer self-update --rollback to return to version 2.1.9
Removing intermediate container 60cbf23b305b
 ---> 5161b4707940
Step 7/8 : RUN     echo "Enabling FFI for all operations ..." &&     echo "ffi.enable=on" >> /etc/php.ini
 ---> Running in 3e853d392749
Enabling FFI for all operations ...
Removing intermediate container 3e853d392749
 ---> bb2a26ab91b9
Step 8/8 : CMD /tmp/startup.sh
 ---> Running in ff4cefb2c01e
Removing intermediate container ff4cefb2c01e
 ---> 1edb35940be6
Successfully built 1edb35940be6
Successfully tagged php8tips/php8_tips_image_php8_latest:latest
```

**Comment by lse123** [comment]
Thank you very much 
I will try in 30-min
after the:

docker pull unlikelysource/php8_tips_7_1_interrim:latest
docker run -it unlikelysource/php8_tips_7_1_interrim:latest /bin/bash 
ping -c3 getcomposer.org
composer update

try the 
docker-compose build
?

**Comment by lse123** [comment]
hello,
I re-run: **docker-compose build**, without your command code, to see the error again, but now the error is different, well?
`
leonidas@ubuntu:~/Documents/DockerPHP8x/repo$ docker-compose build
Building php8-tips-php7
Step 1/7 : FROM unlikelysource/php8_tips_7_1_interrim:latest
 ---> a47711b81daf
Step 2/7 : MAINTAINER doug@unlikelysource.com
 ---> Using cache
 ---> 404142eb65a4
Step 3/7 : COPY php8_tips.sql /tmp/php8_tips.sql
 ---> Using cache
 ---> 1d471d0ff5c1
Step 4/7 : COPY startup.sh /tmp/startup.sh
 ---> Using cache
 ---> 95620076505e
Step 5/7 : RUN     echo "Restoring sample database ..." &&     /etc/init.d/mysql start &&     sleep 7 &&     mysql -uroot -e "SOURCE /tmp/php8_tips.sql;" php8_tips
 ---> Using cache
 ---> 0801a2f118a8
Step 6/7 : RUN     echo "Updating Composer 1.x ..." &&     /usr/bin/composer self-update
 ---> Using cache
 ---> 63566dd8ca46
Step 7/7 : CMD /tmp/startup.sh
 ---> Using cache
 ---> c03acfbda451
Successfully built c03acfbda451
Successfully tagged php8tips/php8_tips_image_php7_latest:latest
Building php8-tips-php8
Step 1/8 : FROM unlikelysource/php8_tips_8_0_interrim:latest
 ---> b2b0c48e52b8
Step 2/8 : MAINTAINER doug@unlikelysource.com
 ---> Using cache
 ---> 4d9ca04102b3
Step 3/8 : COPY php8_tips.sql /tmp/php8_tips.sql
 ---> Using cache
 ---> 2f35d6c6d32d
Step 4/8 : COPY startup.sh /tmp/startup.sh
 ---> Using cache
 ---> 3d86ca811a13
Step 5/8 : RUN     echo "Restoring sample database ..." &&     /etc/init.d/mysql start &&     sleep 7 &&     mysql -uroot -e "SOURCE /tmp/php8_tips.sql;" php8_tips
 ---> Running in 55ae02d411de
Restoring sample database ...
  *  Starting MySQL daemon...                                          [  OK  ]
    
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)
ERROR: Service 'php8-tips-php8' failed to build: The command '/bin/sh -c echo "Restoring sample database ..." &&     /etc/init.d/mysql start &&     sleep 7 &&     mysql -uroot -e "SOURCE /tmp/php8_tips.sql;" php8_tips' returned a non-zero code: 1
leonidas@ubuntu:~/Documents/DockerPHP8x/repo$ 
leonidas@ubuntu:~/Documents/DockerPHP8x/repo$ 

`

**Comment by dbierer** [comment]
Leonidas, pull the PHP 8 image and see if this helps:
```
docker pull unlikelysource/php8_tips_8_0_interrim:latest
docker-compose build
```
Also, can you tell me what type of computer you are using?  
It's possible that your architecture isn't fully supported by Docker.

**Comment by lse123** [comment]
Hello, i use Docker in Ubuntu Studio OS 20.04.3 as a Virtual Machine, in Windows10 Pro host, using VMWARE workstation pro 15.x...

**Comment by dbierer** [comment]
Unfortunately I can't support this configuration.  I would suggest that you follow the directions outlined in Chapter 2 of the book for running the examples on Windows.  Install Docker Desktop for Windows, and follow the instructions from there.  If you do that you will find that everything works quite well.  I have extensively tested the configuration running Windows 10 and Docker Desktop for windows.  I am closing this issue now.
